name: Rust

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install openssl
      if: matrix.os == 'ubuntu-16.04'
      run: |
        sudo apt-get update
        sudo apt-get install libssl-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

