name: Rust

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  dist_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: cargo install --path . --root=installed
